server:
  port: 8090
spring:
  profiles:
    include: common
  datasource:
    url: jdbc:mysql://localhost:3306/hostinghub
    username: root
    password: Mamatha@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  aop:
    proxy-target-class: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pbtjava@gmail.com
    password: jcnsrxqjifkrvqxl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: true
