server:
  port: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/efilingbazaar
    username: root
    password: 1309
  jpa:
    hibernate:
      ddl-auto: update # Disable automatic schema generation
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    dialect: org.hibernate.dialect.MySQL8Dialect
  aop:
    proxy-target-class: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: pbtjava@gmail.com
    password: jcnsrxqjifkrvqxl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
file:
  upload:
    path: 'C:/EfilingImages/test/resources/'

  main:
    allow-circular-references: true

  # Multipart configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB


  thymeleaf:
    cache: false
