server:
  port: 8091
spring:
  profiles:
    include: common
  datasource:
    url: jdbc:mysql://localhost:3306/pmp
    username: root
    password: 1309
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  aop:
    proxy-target-class: true
    thymeleaf:
      cache: true


