server:
  port: 8080
spring:
  profiles:
    include: common
  datasource:
    url: jdbc:mysql://localhost:3306/hostinghub
    username: root
    password: 1309
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


service:
  hosting-hub-userName-uri: http://localhost:8090/admin/userName/